dsp.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp.c -o dsp.lo 
kernel/main.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/extended/fcall.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/extended/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/extended/fcall.c -o kernel/extended/fcall.lo 
kernel/require.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /home/daniel/Desarrollos/www/dsp/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/kernel/exit.c -o kernel/exit.lo 
dsp/tornadohttp/exception/http/clienterrorexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/clienterrorexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/clienterrorexception.zep.c -o dsp/tornadohttp/exception/http/clienterrorexception.lo 
dsp/tornadohttp/exception/http/internalservererrorexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/internalservererrorexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/internalservererrorexception.zep.c -o dsp/tornadohttp/exception/http/internalservererrorexception.lo 
dsp/tornadohttp/container/injectcontainerinterface.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/container/injectcontainerinterface.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/container/injectcontainerinterface.zep.c -o dsp/tornadohttp/container/injectcontainerinterface.lo 
dsp/tornadohttp/middleware/middlewareinterface.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/middleware/middlewareinterface.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/middleware/middlewareinterface.zep.c -o dsp/tornadohttp/middleware/middlewareinterface.lo 
dsp/tornadohttp/resolver/resolverinterface.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/resolver/resolverinterface.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/resolver/resolverinterface.zep.c -o dsp/tornadohttp/resolver/resolverinterface.lo 
dsp/tornadohttp/application.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/application.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/application.zep.c -o dsp/tornadohttp/application.lo 
dsp/tornadohttp/exception/http/badgatewayexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/badgatewayexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/badgatewayexception.zep.c -o dsp/tornadohttp/exception/http/badgatewayexception.lo 
dsp/tornadohttp/exception/http/badrequestexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/badrequestexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/badrequestexception.zep.c -o dsp/tornadohttp/exception/http/badrequestexception.lo 
dsp/tornadohttp/exception/http/conflictexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/conflictexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/conflictexception.zep.c -o dsp/tornadohttp/exception/http/conflictexception.lo 
dsp/tornadohttp/exception/http/forbiddenexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/forbiddenexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/forbiddenexception.zep.c -o dsp/tornadohttp/exception/http/forbiddenexception.lo 
dsp/tornadohttp/exception/http/methodnotallowedexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/methodnotallowedexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/methodnotallowedexception.zep.c -o dsp/tornadohttp/exception/http/methodnotallowedexception.lo 
dsp/tornadohttp/exception/http/notacceptableexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/notacceptableexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/notacceptableexception.zep.c -o dsp/tornadohttp/exception/http/notacceptableexception.lo 
dsp/tornadohttp/exception/http/notfoundexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/notfoundexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/notfoundexception.zep.c -o dsp/tornadohttp/exception/http/notfoundexception.lo 
dsp/tornadohttp/exception/http/paymentrequiredexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/paymentrequiredexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/paymentrequiredexception.zep.c -o dsp/tornadohttp/exception/http/paymentrequiredexception.lo 
dsp/tornadohttp/exception/http/preconditionfailedexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/preconditionfailedexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/preconditionfailedexception.zep.c -o dsp/tornadohttp/exception/http/preconditionfailedexception.lo 
dsp/tornadohttp/exception/http/requestentitytoolargeexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/requestentitytoolargeexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/requestentitytoolargeexception.zep.c -o dsp/tornadohttp/exception/http/requestentitytoolargeexception.lo 
dsp/tornadohttp/exception/http/serviceunavailableexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/serviceunavailableexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/serviceunavailableexception.zep.c -o dsp/tornadohttp/exception/http/serviceunavailableexception.lo 
dsp/tornadohttp/exception/http/toomanyrequestexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/toomanyrequestexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/toomanyrequestexception.zep.c -o dsp/tornadohttp/exception/http/toomanyrequestexception.lo 
dsp/tornadohttp/exception/http/unauthorizedexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/unauthorizedexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/http/unauthorizedexception.zep.c -o dsp/tornadohttp/exception/http/unauthorizedexception.lo 
dsp/tornadohttp/exception/middlewareexception.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/middlewareexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/exception/middlewareexception.zep.c -o dsp/tornadohttp/exception/middlewareexception.lo 
dsp/tornadohttp/middleware/middleware.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/middleware/middleware.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/middleware/middleware.zep.c -o dsp/tornadohttp/middleware/middleware.lo 
dsp/tornadohttp/resolver/resolver.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/resolver/resolver.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/resolver/resolver.zep.c -o dsp/tornadohttp/resolver/resolver.lo 
dsp/tornadohttp/tornadohttp.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/tornadohttp.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/tornadohttp/tornadohttp.zep.c -o dsp/tornadohttp/tornadohttp.lo 
dsp/0__closure.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/0__closure.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/0__closure.zep.c -o dsp/0__closure.lo 
dsp/1__closure.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/1__closure.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/1__closure.zep.c -o dsp/1__closure.lo 
dsp/2__closure.lo: /home/daniel/Desarrollos/www/dsp/ext/dsp/2__closure.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/daniel/Desarrollos/www/dsp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/daniel/Desarrollos/www/dsp/ext/dsp/2__closure.zep.c -o dsp/2__closure.lo 
$(phplibdir)/dsp.la: ./dsp.la
	$(LIBTOOL) --mode=install cp ./dsp.la $(phplibdir)

./dsp.la: $(shared_objects_dsp) $(DSP_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_dsp) $(DSP_SHARED_LIBADD)

