
extern zend_class_entry *dsp_tornadohttp_resolver_resolverinterface_ce;

ZEPHIR_INIT_CLASS(Dsp_TornadoHttp_Resolver_ResolverInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_dsp_tornadohttp_resolver_resolverinterface_solve, 0, 0, 1)
	ZEND_ARG_INFO(0, middleware)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(dsp_tornadohttp_resolver_resolverinterface_method_entry) {
	PHP_ABSTRACT_ME(Dsp_TornadoHttp_Resolver_ResolverInterface, solve, arginfo_dsp_tornadohttp_resolver_resolverinterface_solve)
	PHP_FE_END
};
